[project]
name = "qa_agentic_ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "arwinnahidi", email = "arwinnahidi5277277@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "faiss-cpu>=1.15.1",
    "langchain>=1.4.2",
    "langchain-anthropic>=1.7.2",
    "langchain-community>=0.4.2",
    "langchain-core>=1.6.3",
    "langchain-openai>=1.6.2",
    "langgraph>=1.2.11",
    "python-dotenv>=1.2.3",
]

[project.scripts]
qa_agentic_ai = "qa_agentic_ai:main"

[tool.uv]
package = false
